name: Format

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.11"

jobs:
  sort:
    name: sort testdata
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: 🚀 Sort test response data
        run: |
          find './tests/response' \
            -maxdepth '1' \
            -type 'f' \
            -name '*.json' \
            -exec sh -c 'mv $1 $1.tmp; jq ".data|=sort_by(.feature)" --sort-keys $1.tmp > $1; rm $1.tmp' shell {} ";"
      - name: 🔍 Verify
        run: git diff --name-only --exit-code

  deprecations:
    name: validate deprecation database
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Update deprecation database
        run: python check_deprecations.py --update
      - name: Verify no changes
        run: git diff --exit-code
        if: always()
