name: Format

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.11"

jobs:
  sort:
    name: sort testdata
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: 🚀 Sort test response data
        run: |
          find './tests/response' \
            -maxdepth '1' \
            -type 'f' \
            -name '*.json' \
            -exec sh -c 'mv $1 $1.tmp; jq ".data|=sort_by(.feature)" --sort-keys $1.tmp > $1; rm $1.tmp' shell {} ";"
      - name: 🔍 Verify
        run: git diff --name-only --exit-code

  deprecations:
    name: validate deprecation database
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Update deprecation database
        run: python check_deprecations.py --update
      - name: Verify no changes
        run: git diff --exit-code
        if: always()
