name: Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 🏗 Set up UV
        uses: astral-sh/setup-uv@1c37ad07a6a961277cf70c0d37d6f313000f5884 # v10.3.0
      - name: 🏗 Install dependencies
        run: uv sync --frozen --no-progress
      - name: 🚀 Check code for common misspellings
        run: uv run --frozen codespell **/*.py

  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 🏗 Set up UV
        uses: astral-sh/setup-uv@1c37ad07a6a961277cf70c0d37d6f313000f5884 # v10.3.0
      - name: 🏗 Install dependencies
        run: uv sync --frozen --no-progress
      - name: 🚀 Run ruff linter
        run: uv run --frozen ruff check --output-format=github .
    #   - name: 🚀 Run ruff formatter
    #     run: poetry run ruff format --check .

  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 🏗 Set up UV
        uses: astral-sh/setup-uv@1c37ad07a6a961277cf70c0d37d6f313000f5884 # v10.3.0
      - name: 🏗 Install dependencies
        run: uv sync --frozen --no-progress
      - name: 🚀 Run pylint
        run: uv run --frozen pylint **/*.py
