name: Test

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  pytest:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 🏗 Set up UV
        uses: astral-sh/setup-uv@1c37ad07a6a961277cf70c0d37d6f313000f5884 # v10.3.0
        with:
          python-version: ${{ matrix.python }}
      - name: 🏗 Install dependencies
        run: uv sync --frozen --no-progress
      - name: 🚀 Run pytest
        run: uv run --frozen pytest --cov PyViCare
      - name: ⬆️ Upload coverage artifact
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: coverage-${{ matrix.python }}
          path: .coverage
